---
services:
  database:
    container_name: postgresql
    networks:
      - psql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always
    image: postgres:${PSQL_TAG}
    volumes:
      - ./database/cache/postgres-data/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  psql:
    name: psql_default
    driver: bridge
...